#!/usr/bin/env bash
# Displays "Best School" 10 times with "Hi" after the 9th line

i=0

while [ $i -lt 10 ]
do
	if [[ $i -eq 8 ]]
then
	echo "Best School"
	echo "Hi"
else
	echo "Best School"
fi
	(( i++ ))
done
