#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
# Displays 4 then "badluck from china"
# Displays 9 then "badluck from Japan"
# Displays 17 then "badluck from Italy"

i=1

while [ $i -le 20 ]
do
	echo $i
	case $i in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
	esac
	(( i++ ))
done
